### ISSUE TITLE
Anpassen des Tech-Stacks

### ISSUE THREAD

**Issue by pplayer1712** [DHBW-UMOC/UMOC#2]
Max bitte passe den Tech-Stack an die besprochenen Optionen an!

**Comment by Max-Rohrhirsch** [comment]
Also *Klatschen*, beim Backend wurde bisher Spring Boot mit Kotlin verwendet. Nach einiger Besprechung im Team bleiben wir erstmal dabei, da man immer noch Java Dateien erstellen kann und diese in Kotlin importieren. @wraith044 kann ebenfalls Kotlin und könnte zur Not den Code verstehen und debuggen. Wenn es doch zu schlimm wird, meldet sich @Max-Rohrhirsch dazu, die ganze Anwendung in Java umzuwandeln. Wir hoffen, das Problem hat sich hiermit für Sie gelöst.
